### ISSUE TITLE
it doesn't work for me 

### ISSUE THREAD

**Issue by zzzgit** [jest-community/eslint-plugin-jest#245]
```yml
env:
  node: true
  commonjs: true
  es6: true
  jest: true
plugin:
  - 'jest'
rules:
  jest/no-identical-title: 
    - error

```

I don't know why it doesn't work.
I have installed `eslint` and `eslint-plugin-jest` also.
